### ISSUE TITLE
Code Examples , Router

### ISSUE THREAD

**Issue by stanRepo** [theonejonahgold/web-app-from-scratch-2021#12]
Including code examples in your README.md will improve on the clarity of your diagrams. 
Since you've written your own SPA Router, it's a bummer if people don't notice it while visiting your repository.

**Comment by jonahgoldwastaken** [comment]
I'll create another repository for the handlebars router and state management. I don't think the code examples fit in this repository, as it's not about implementing my router somewhere else.
