### ISSUE TITLE
Peer review #2

### ISSUE THREAD

**Issue by NathanNeelis** [theonejonahgold/web-app-from-scratch-2021#2]
## Repo
✅  Link in the repo  
✅  Concept is described well in the readme  
✅  API is described in the readme  
🍊 Actor is included, interaction diagram not yet  

#### Do the actors make sense to you?
Kijk of je de Actor diagram iets kan versimpelen  
Ook door de lijntjes te volgen kom ik er niet helemaal uit.  

#### Click through the live demo
Werkt prima! leuk gedaan.
Alleen even handig om nog even aan te geven is dat je ook de provincie in moet voeren.  

#### Browse the code
Wauw zeg! Ik ben er door heen gelopen, en ik begrijp zeker de helft niet :) 
Maar ik zie wel de volgende tops:
* Geen global variabelen, nice!
* Alle functies zien er goed genest uit.
* Extreem veel gebruik van modules. Hier helpt je actor diagram dan wel bij, want dan begrjip ik een beetje wat bij wat hoort. 
* Ik zie dat je routes heb gebruikt.
  
Mogelijke tip:  
* Ik zie dat je nog ergens een .innterHTML gebruikt, volgens de best practices is dat niet altijd optimaal. Moet ik er wel bij zeggen dat ik niet helemaal weet of dit in jouw code ook zo is.  
`https://github.com/theonejonahgold/web-app-from-scratch-2021/blob/f0dfa01b0db9c15fa9e45a7157e91d069cc04df2/scripts/modules/router.js#L26`

Verder:  
Je code ziet er gewoon heel goed uit, en een beetje te next-level voor mij om daar echt verbeteringen in te kunnen vinden. Of zelfs om alles te begrijpen :)

**Comment by jonahgoldwastaken** [comment]
Yoo Nathan,

Ik gebruik nu Bing Maps, dus een provincie is niet vereist. 😄 De actor en interaction diagrams zijn nu een stuk simpeler, met de basis die er echt toe doet.

Die innerHTML is volgens mij hier verplicht, omdat ik in een Handlebars template als string in de div met id app gooi.

Thanks voor het compliment! Ik hoop dat het niet al te intimiderend was 😅
