### ISSUE TITLE
Code review week 2

### ISSUE THREAD

**Issue by RobinFrugte97** [theonejonahgold/web-app-from-scratch-2021#3]
Hey Jonah!

Ik krijg het niet voor elkaar om een route te fetchen. Denk dat je wat meer guidance moet geven aan de gebruiker wat je precies verwacht in de inputvelden. Placeholder of misschien twee aparte inputs voor de provincies (volgens mij had je die nodig) om het duidelijk te maken aan de gebruiker.

Uitgebreide actor diagram! (Niet dark-mode vriendelijk helaas :P) Probeer je actor diagram wel duidelijk en overzichtelijk te houden als je hem zo uitgebreid maakt. Misschien kun je de groepering een andere kleur geven? De lijnen zijn lastig te volgen.

Voor de rest een nette readme. Kan je goed op bouwen denk ik.

Misschien kun je je repo een beetje opschonen door de dingen uit de originele fork te verwijderen, zoals examples en course. Dit schept wat meer ruimte en orde.

Klopt het dat contants en helpers hetzelfde zijn? Je hebt zoveel modules!

Super veel modules, erg georganiseerd! Ik heb echt niks aan te merken op je code, super clean allemaal! Je hebt een reduce gebruikt zie ik, netjes. Volgens mij voldoe je code-wise aan alle eisen voor dit vak.

Kijk nog even naar je diagrams.

Gaat volgens mij wel lekker, ga zo door!

**Comment by jonahgoldwastaken** [comment]
Hey Robin,

Dit is wat ik heb gedaan met je feedback:

- De diagrams zijn een stuk versimpeld, en nu ook af.
- Mappen uit de originele repo heb ik verwijderd.
- De departure en arrival inputs zijn nu gekoppeld aan Bing Maps, dus je kan nu zelfs een bedrijfsnaam invoeren en het werkt!
- 'contants' is hernoemd naar 'constants', want het zijn constante waardes. Ik weet in ieder geval zeker dat ik geen dyslexie heb nu. Heb er al die tijd overheen gekeken.
