### ISSUE TITLE
What happens when I click on 'generate list' without selecting any numbers?

### ISSUE THREAD

**Issue by suustenvoorde** [theonejonahgold/web-app-from-scratch-2021#4]
Give the user more feedback. Your app is really complex and the code is on a high level. Add some more feedback to the user (and some styling would be awesome..... ) to show more about your great SPA!

**Comment by jonahgoldwastaken** [comment]
@solideagency I added a whole lot of nice interaction in the new design I just published. Be sure to check it out [here](https://triptop.app)!
