### ISSUE TITLE
freshTracks

### ISSUE THREAD

**Issue by suustenvoorde** [theonejonahgold/web-app-from-scratch-2021#8]
https://github.com/theonejonahgold/web-app-from-scratch-2021/blob/fa7161625ba7147397f7d935bf5ff58ddc18eba8/scripts/routes/generator.js#L66

Do you mean the topTwentyTracks?

**Comment by jonahgoldwastaken** [comment]
I meant newTracks, as they are a fresh batch of new recommended tracks to filter over 😊
